import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Dark premium theme — all semantic names preserved for drop-in compatibility
        'background':                 '#08080f',
        'on-background':              '#eeeeff',
        'surface':                    '#0d0d1a',
        'on-surface':                 '#e8e8fa',
        'surface-container-lowest':   '#04040a',
        'surface-container-low':      '#0a0a14',
        'surface-container':          '#0f0f1d',
        'surface-container-high':     '#151528',
        'surface-container-highest':  '#1c1c33',
        'surface-dim':                '#040408',
        'surface-bright':             '#1a1a2e',
        'surface-variant':            '#13132a',
        'surface-tint':               '#7c7ffa',
        'on-surface-variant':         '#7878a8',
        'outline':                    '#2a2a50',
        'outline-variant':            '#1a1a35',
        'inverse-surface':            '#e8e8ff',
        'inverse-on-surface':         '#0f0f1d',
        'inverse-primary':            '#c0c1ff',
        // Primary (indigo/blue — brightened for dark bg)
        'primary':                    '#7c7ffa',
        'on-primary':                 '#ffffff',
        'primary-container':          '#1e1e8a',
        'on-primary-container':       '#c8c8ff',
        'primary-fixed':              '#e0e0ff',
        'primary-fixed-dim':          '#a0a0ff',
        'on-primary-fixed':           '#07006c',
        'on-primary-fixed-variant':   '#2f2ebe',
        // Secondary (sky blue)
        'secondary':                  '#38bdf8',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#0369a1',
        'on-secondary-container':     '#e0f2fe',
        'secondary-fixed':            '#e0f2fe',
        'secondary-fixed-dim':        '#bae6fd',
        'on-secondary-fixed':         '#001a42',
        'on-secondary-fixed-variant': '#004395',
        // Tertiary (purple — brightened for dark bg)
        'tertiary':                   '#c084fc',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#5b21b6',
        'on-tertiary-container':      '#f3e8ff',
        'tertiary-fixed':             '#f3e8ff',
        'tertiary-fixed-dim':         '#d8b4fe',
        'on-tertiary-fixed':          '#2c0051',
        'on-tertiary-fixed-variant':  '#6900b3',
        // Error
        'error':                      '#f87171',
        'error-container':            '#450a0a',
        'on-error':                   '#ffffff',
        'on-error-container':         '#fecaca',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        'container-max': '1280px',
        gutter: '20px',
        xl: '64px',
        md: '24px',
        sm: '16px',
        xs: '8px',
        lg: '40px',
      },
      maxWidth: { 'container-max': '1280px' },
      fontFamily: {
        'label-caps': ['IBM Plex Sans', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
        'h1':         ['Inter', 'sans-serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'h2':         ['Inter', 'sans-serif'],
        display:      ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em',  fontWeight: '600' }],
        'body-lg':    ['18px', { lineHeight: '1.6', letterSpacing: '0',      fontWeight: '400' }],
        'h1':         ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em',fontWeight: '700' }],
        'body-md':    ['16px', { lineHeight: '1.6', letterSpacing: '0',      fontWeight: '400' }],
        'h2':         ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em',fontWeight: '600' }],
        display:      ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em',fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};

export default config;
